# OP-ETL v2.0 Configuration
# Single, unified configuration file with explicit settings

workspace:
  downloads: "./data/downloads"
  staging_gdb: "./data/staging.gdb"
  sde_connection: "./data/connections/prod.sde"

processing:
  target_wkid: 3006  # SWEREF99 TM
  aoi_bbox: [610000, 6550000, 700000, 6650000]  # Strängnäs area in SWEREF99 TM
  aoi_bbox_wkid: 3006

sources:
  # Test with a representative set of sources for baseline capture
  
  # OGC API Features source (requires explicit geometry)
  - name: "erosion_areas"
    type: "ogc"
    url: "https://api.sgu.se/oppnadata/stranderosion-kust/ogc/features/v1/"
    authority: "SGU"
    geometry: "POLYGON"  # Required for GeoJSON sources
    collections: ["aktiv-erosion"]
    enabled: true

  # ArcGIS REST API source
  - name: "riksintressen"
    type: "rest"
    url: "https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/LST/lst_lst_riksintressen_4/MapServer"
    authority: "LST"
    layer_ids: [0]
    enabled: true

  # HTTP file download
  - name: "geodata_zip"
    type: "http"
    url: "https://www.forsvarsmakten.se/siteassets/geodata/rikstackande-geodata.zip"
    authority: "FM"
    enabled: true

  # WFS source (requires explicit geometry)
  - name: "nature_reserves"
    type: "wfs"
    url: "https://geodata.naturvardsverket.se/nedladdning/naturvardsregistret/"
    authority: "NVV"
    geometry: "POLYGON"
    collections: ["NR"]
    enabled: false  # Disabled for initial testing

  # ATOM feed source
  - name: "environmental_data"
    type: "atom"
    url: "https://www.lantmateriet.se/atom/inspire/ds/cp/CP.xml"
    authority: "LM"
    enabled: false  # Disabled for initial testing