processing:
  aoi_bbox:
  - 610000
  - 6550000
  - 700000
  - 6650000
  aoi_bbox_wkid: 3006
  target_wkid: 3006
sources:
- authority: SGU
  collections:
  - erosion
  enabled: true
  geometry: POLYGON
  name: erosion_areas
  type: ogc
  url: https://api.sgu.se/features/v1/
- authority: LST
  enabled: true
  layer_ids:
  - 0
  - 1
  name: riksintressen
  type: rest
  url: https://services.example.com/arcgis/rest/services/Data/MapServer
workspace:
  downloads: ./data/downloads
  sde_connection: ./data/prod.sde
  staging_gdb: ./data/staging.gdb
