# Global defaults for bbox filtering (inherited by sources that don't specify their own)
# Updated to use SWEREF99 TM (EPSG:3006) for REST APIs as best practice
defaults:
  # Strängnäs region in SWEREF99 TM coordinates (meters)
  bbox: [610000, 6550000, 700000, 6650000]
  bbox_sr: 3006

  # For OGC APIs that don't support EPSG:3006, use CRS84
  ogc_bbox: [16.4733147, 59.0678531, 17.6430658, 59.6406047]
  ogc_bbox_sr: "CRS84"

sources:
#---------------------------------------------------#
#                FM - Försvarsmakten                #
#---------------------------------------------------#

- name: Försvarsmakten - Rikstäckande geodata
  authority: FM
  type: file
  url: 
    https://www.forsvarsmakten.se/siteassets/2-om-forsvarsmakten/samhallsplanering/geodata/rikstackande-geodata-forsvarsmakten.zip
  enabled: false

#-----------------------------------------------------#
#                NVV - Naturvårdsverket               #
#-----------------------------------------------------#

- name: Naturvårdsverket - Naturvårdsregistret
  authority: NVV
  type: file
  url: https://geodata.naturvardsverket.se/nedladdning/naturvardsregistret/
  enabled: false
  raw:
    layer_name:
    - Biosfarsomraden
    - DVO
    - HELCOM
    - IF
    - KR
    - LBSO
    - NP
    - NR
    - NVA
    - NVO
    - Nationalparksplan
    - OBO
    - OSPAR
    - Ramsar_2018
    - SCI_Rikstackande
    - SPA_Rikstackande
    - TILLTRADESFORBUD
    - VSO
    - Varldsarv

#---------------------------------------------------#
#                LST - Länsstyrelsen                #
#---------------------------------------------------#

- name: Miljöriskområde
  authority: LST
  type: atom
  url: https://ext-dokument.lansstyrelsen.se/gemensamt/geodata/ATOM/ATOM_lst.LST_Miljoriskomrade.xml
  enabled: false
  raw:
    filter_services: true  # Enable bbox filtering for referenced services
- name: 'Vindkraftskollen: Vindkraftverk'
  authority: LST
  type: atom
  url: https://ext-dokument.lansstyrelsen.se/gemensamt/geodata/ATOM/ATOM_lst.vbk_vindkraftverk.xml
  enabled: false
  raw:
    filter_services: true  # Enable bbox filtering for referenced services
- name: 'Vindkraftskollen: Projekteringsområden'
  authority: LST
  type: atom
  url: https://ext-dokument.lansstyrelsen.se/gemensamt/geodata/ATOM/ATOM_lst.vbk_projekteringsomraden.xml
  enabled: false
- name: Potentiellt förorenade områden
  authority: LST
  type: file
  url: 
    https://ext-dokument.lansstyrelsen.se/Gemensamt/Geodata/Datadistribution/SWEREF99TM/EBH_Potentiellt_fororenade_omraden.zip
  enabled: false
- name: Riksintressen
  authority: LST
  type: rest
  url: https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/LST/lst_lst_riksintressen_4/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 0
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: Riksintressen - Vindbruk
  authority: LST
  type: rest
  url: https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/LST/lst_lst_riksintressen_vindbruk_4/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006

#-------------------------------------------------------------#
#                LSTD - Länsstyrelsen Södermanland            #
#-------------------------------------------------------------#

- name: LstD Föreskrifter
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Foreskrifter_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Fysisk planering
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Fysisk_planering_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Ett rikt odlingslandskap
  authority: LSTD
  type: rest
  url: 
    https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Ett_rikt_odlingslandskap_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 2
    - 3
    - 4
    - 5
    - 6
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Friluftsliv
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Friluftsliv_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 0
    - 1
    - 2
    - 3
    - 4
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD God bebyggd miljö
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_God_bebyggd_miljo_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Hav i balans
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Hav_i_balans_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Levande sjöar och vattendrag
  authority: LSTD
  type: rest
  url: 
    https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Levande_sjoar_och_vattendrag_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 2
    - 3
    - 7
    - 8
    - 9
    - 10
    - 11
    - 12
    - 13
    - 14
    - 15
    - 16
    - 17
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Levande skogar
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Levande_skogar_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 0
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Klimat
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Klimat_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 2
    - 3
    - 4
    - 5
    - 6
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Kulturmiljö
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Kulturmiljo_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 1
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Markavvattning
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Markavvattning_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 2
    - 3
    - 4
    - 5
    - 6
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Markstabilitet
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Markstabilitet_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Naturkartläggning
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Naturkartlaggning_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Skog och träd
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Skog_och_trad_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD GI Värdetrakter våtmark
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_GI_Myllrande_vatmarker_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: LstD Strandskydd
  authority: LSTD
  type: rest
  url: https://ext-geodata-lokala-visning.lansstyrelsen.se/arcgis/rest/services/LSTD/LstD_Strandskydd_EXT/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006

#-------------------------------------------------------------------------#
#                MSB - Myndigheten för samhällsskydd och beredskap        #
#-------------------------------------------------------------------------#

- name: Skyddsrum
  authority: MSB
  type: file
  url: https://inspire.msb.se/nedladdning/filer/shape/Skyddsrum.zip
  enabled: false

#---------------------------------------------------------#
#                RAA - Riksantikvarieämbetet              #
#---------------------------------------------------------#

- name: Riksintresse Kulturmiljövård MB3kap6
  authority: RAA
  type: atom
  url: https://ext-dokument.lansstyrelsen.se/gemensamt/geodata/ATOM/ATOM_raa.RAA_RI_kulturmiljovard_MB3kap6.xml
  enabled: false
- name: RAA Byggnader Sverige
  authority: RAA
  type: file
  url: https://pub.raa.se/nedladdning/datauttag/bebyggelse/byggnader_kulthist_inv/byggnader_sverige.gpkg
  out_name: byggnader_sverige
  enabled: false
  raw:
    layer_name: byggnader_sverige_point
- name: Enskilda och statliga byggnadsminnen, skyddsområden
  authority: RAA
  type: file
  url: https://pub.raa.se/nedladdning/datauttag/bebyggelse/byggnadsminne_skyddsomr/skyddsomrade_byggnadsminne_sverige.gpkg
  out_name: skyddsomrade_byggnadsminne_sverige
  enabled: false
  raw:
    layer_name: skyddsomrade_byggnadsminne_sverige_polygon
- name: Kulturhistoriska lämningar, Södermanland
  authority: RAA
  type: file
  url: https://pub.raa.se/nedladdning/datauttag/lamningar/lan/l%C3%A4mningar_l%C3%A4n_s%C3%B6dermanland.gpkg
  out_name: lämningar_län_södermanland
  enabled: false
  raw:
    layer_name: lämningar_län_södermanland_point
- name: RAA Världsarv i Sverige
  authority: RAA
  type: file
  url: https://pub.raa.se/nedladdning/datauttag/varldsarv/varldsarv_sverige.gpkg
  out_name: varldsarv_sverige
  enabled: false
  raw:
    layer_name: varldsarv_sverige_polygon

#-------------------------------------------------------------#
#                SGI - Statens geotekniska institut           #
#-------------------------------------------------------------#

- name: Inträffade skred, ras och övriga jordrörelser (skreddatabas)
  authority: SGI
  type: file
  url: https://gis.sgi.se/dokument/geodatasezip/SGI_Skreddatabas_ver2.zip
  enabled: false

#---------------------------------------------------------------#
#                SGU - Sveriges geologiska undersökning         #
#---------------------------------------------------------------#

- name: Erosion
  authority: SGU
  type: ogc
  url: https://api.sgu.se/oppnadata/stranderosion-kust/ogc/features/v1/collections/
  enabled: true
  raw:
    collections:
    - aktiv-erosion
    - erosionsforhallande-plus1m
    - erosionsforhallande-strand
    - erosionsskydd
    - oversvamningsskydd
    - vattenyta-prognos
    page_size: 1000
    supports_bbox_crs: true
    # SR configuration for OGC API - defaults to CRS84, stage in WGS84, target SWEREF99 TM
    supports_epsg_3006: false
    bbox_crs: CRS84
    stage_sr: 4326
    target_sr: 3006
- name: Brunnar
  authority: SGU
  type: ogc
  url: https://api.sgu.se/oppnadata/brunnar/ogc/features/v1/collections/
  enabled: true
  raw:
    collections:
    - brunnar
    - brunnar-lager
    page_size: 1000
    supports_bbox_crs: true
    # SR configuration for OGC API - defaults to CRS84, stage in WGS84, target SWEREF99 TM
    supports_epsg_3006: false
    bbox_crs: CRS84
    stage_sr: 4326
    target_sr: 3006
- name: Jordskred och raviner
  authority: SGU
  type: ogc
  url: https://api.sgu.se/oppnadata/jordskred-raviner/ogc/features/v1/collections/
  enabled: true
  raw:
    collections:
    - jordskred-raviner
    page_size: 1000
    supports_bbox_crs: true
- name: Grus Krossberg
  authority: SGU
  type: ogc
  url: https://api.sgu.se/oppnadata/grus-krossberg/ogc/features/v1/collections
  enabled: true
  raw:
    collections:
    - grus-grus
    - grus-berg
    - grus-moran
    page_size: 1000
    supports_bbox_crs: true

#-------------------------------------------------#
#                SJV - Jordbruksverket            #
#-------------------------------------------------#

- name: Jordbruksblock (2024)
  authority: SJV
  type: rest
  url: https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/SJV/lst_sjv_fak04jbb/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 18
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: Ängs- och betesmarksinventeringen
  authority: SJV
  type: rest
  url: https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/SJV/lst_sjv_fak04ovr/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 4
    - 5
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006

#-----------------------------------------------#
#                SKS - Skogsstyrelsen           #
#-----------------------------------------------#

- name: Naturvärden
  authority: SKS
  type: file
  url: https://geodpags.skogsstyrelsen.se/geodataport/data/sksNaturvarden_gpkg.zip
  enabled: false
  download_format: zip
- name: Ras och skred
  authority: SKS
  type: rest
  url: https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaRasoskred/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 2  # Instabila slänter - Mycket kraftig lutning
#    - 3  # Angränsande slänter med kraftig lutning
    - 4  # Slänter - Område som kan påverkas vid ras
    - 6  # Ravinformation - Möjlig ravinformation
    - 7  # Ravinformation - Vattendrag i anslutning
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: Skogsstyrelsen - Biotopskydd (REST)
  authority: SKS
  type: rest
  url: https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaBiotopskydd/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    in_sr: 3006
    out_sr: 3006
    bbox_sr: 3006
- name: Utförda avverkningar
  authority: SKS
  type: rest
  url: https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaUtfordavverkning/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    in_sr: 3006
    out_sr: 3006
    bbox_sr: 3006
- name: Naturvårdsavtal
  authority: SKS
  type: rest
  url: https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaNaturvardsavtal/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    in_sr: 3006
    out_sr: 3006
    bbox_sr: 3006
- name: Återvätningsavtal
  authority: SKS
  type: rest
  url: https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaAtervatningavtal/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    in_sr: 3006
    out_sr: 3006
    bbox_sr: 3006
- name: Nyckelbiotoper
  authority: SKS
  type: rest
  url: https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaNyckelbiotop/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    in_sr: 3006
    out_sr: 3006
    bbox_sr: 3006
- name: Sumpskogar
  authority: SKS
  type: rest
  url: https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaSumpskog/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    in_sr: 3006
    out_sr: 3006
    bbox_sr: 3006
- name: Avverkningsanmälda områden
  authority: SKS
  type: rest
  url: https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaAvverkningsanmalan/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    in_sr: 3006
    out_sr: 3006
    bbox_sr: 3006
- name: Gräns för skogsskyddsbestämmelser
  authority: SKS
  type: rest
  url: https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaSkogsskyddsbestammelser/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    in_sr: 3006
    out_sr: 3006
    bbox_sr: 3006
- name: Nyckelbiotoper - storskogsbruket
  authority: SKS
  type: rest
  url: https://geodpags.skogsstyrelsen.se/arcgis/rest/services/Geodataportal/GeodataportalVisaSkogsbruknyckelbiotop/MapServer
  enabled: false
  raw:
    response_format: json
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006

#-----------------------------------------------#
#                SVK - Svenska kraftnät         #
#-----------------------------------------------#

- name: Stamnät
  authority: SVK
  type: file
  url: https://gis-services.metria.se/svkfeed/filer/SVK_STAMNAT.zip
  enabled: false

#---------------------------------------------#
#                TRV - Trafikverket           #
#---------------------------------------------#

- name: Vägar
  authority: TRV
  type: rest
  url: https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/TV/lst_tv_fak01/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 0
    - 1
    - 2
    bbox_sr: 3006
    in_sr: 3006
    out_sr: 3006
- name: Övrigt
  authority: TRV
  type: rest
  url: https://ext-geodata-nationella.lansstyrelsen.se/arcgis/rest/services/TV/lst_tv_fak06/MapServer
  enabled: false
  raw:
    response_format: json
    layer_ids:
    - 2
    in_sr: 3006
    out_sr: 3006
    bbox_sr: 3006
